version: '3'

services:

  #PHP service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laragram_web
    image: laragram
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www/
      - ./docker_conf/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: laragram_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/
      - ./docker_conf/nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  db:
    image: mysql:5.7.26
    container_name: laragram_db
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=laragram
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=laragram
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker_conf/mysql/my.cnf:/etc/mysql/my.cnf
volumes:
  dbdata:
